### ISSUE TITLE
Gotta have more cowbell

### ISSUE THREAD

**Issue by theothornhill** [asbjornh/synth#1] opened 2021-12-31 22:41 UTC
The amount of cowbell is too low. Fix pls. 

🔔.

**Comment by theothornhill** [comment] 2021-12-31 23:38
Ping. Urgent.

**Comment by asbjornh** [comment] 2022-01-01 03:02
This is by design and already addressed in #1234, # 2345 and #3456

**Closed as completed by asbjornh** 2022-01-01 03:02 UTC
Labels: duplicate, wontfix

**Comment by theothornhill** [comment] 2022-01-01 06:31
Damn. I was told javascript could do anything.
